version: '3.5'

services:

  vehicle-brand-service:
    image: vehicle-brand-service:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - /data/app
    networks:
      - autostreet_shared

networks:
  autostreet_shared:
    external: true
    name: autostreet_shared